/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab3_17986494_Sepulveda;


//import lab3_17986494_Sepulveda.System_17986494_Sepulveda;

public class Main {
    public static void main(String[] args) {        
        System_17986494_Sepulveda mySystem = new System_17986494_Sepulveda();
        
        MenusGeneral_17986494_Sepulveda.menuFirst(mySystem);
        
    }
}
