/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab3_17986494_Sepulveda;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {

}
